#!/usr/bin/env bash
set -euo pipefail
export JAVA_VERSION=$(docker run --rm $IMAGE_NAME sh -l -c 'echo ${JAVA_VERSION}')

for i in ${JAVA_VERSION} ${JAVA_VERSION%.*.*} ${JAVA_VERSION%%.*} ; do
  docker tag $IMAGE_NAME $DOCKER_REPO:$i
  docker push $DOCKER_REPO:$i
done
